const carpoolPosts = [
  {
    id: 1,
    userEmail: "ayush.kumar@college.edu",
    phoneNumber: "919876543210",
    from: "Main Gate",
    to: "Ranchi Railway Station",
    date: "2025-05-20",
    time: "3:30 PM",
    seatsAvailable: 2,
    note: "Leaving after class ends. AC Car 🚘",
    upvotes: 12,
  },
  {
    id: 2,
    userEmail: "priya.s@college.edu",
    phoneNumber: "919812345678",
    from: "Hostel Block C",
    to: "Airport",
    date: "2025-05-21",
    time: "10:00 AM",
    seatsAvailable: 1,
    note: "Cab booked, one seat left. Sharing fare.",
    upvotes: 8,
  },
  {
    id: 3,
    userEmail: "rohan.verma@college.edu",
    phoneNumber: "919999888777",
    from: "Library",
    to: "Bus Stand",
    date: "2025-05-19",
    time: "5:00 PM",
    seatsAvailable: 3,
    note: "Planning to leave right after the study group.",
    upvotes: 5,
  },
  {
    id: 4,
    userEmail: "simran.k@college.edu",
    phoneNumber: "919812398765",
    from: "Mess Area",
    to: "ISBT Ranchi",
    date: "2025-05-22",
    time: "7:15 AM",
    seatsAvailable: 1,
    note: "Early morning trip, please be punctual.",
    upvotes: 10,
  },
  {
    id: 5,
    userEmail: "anand.j@college.edu",
    phoneNumber: "919700112233",
    from: "Parking Lot",
    to: "Railway Station",
    date: "2025-05-20",
    time: "4:45 PM",
    seatsAvailable: 2,
    note: "Petrol expenses to be shared. Fast drive.",
    upvotes: 7,
  },
  {
    id: 6,
    userEmail: "meena.sharma@college.edu",
    phoneNumber: "919821556677",
    from: "Cafeteria",
    to: "Airport",
    date: "2025-05-23",
    time: "12:00 PM",
    seatsAvailable: 1,
    note: "I have one large suitcase, FYI.",
    upvotes: 6,
  },
  {
    id: 7,
    userEmail: "rajiv.nanda@college.edu",
    phoneNumber: "919833344455",
    from: "Admin Block",
    to: "City Center",
    date: "2025-05-18",
    time: "6:00 PM",
    seatsAvailable: 3,
    note: "Chill music playlist guaranteed 🎶",
    upvotes: 14,
  },
  {
    id: 8,
    userEmail: "neha.t@college.edu",
    phoneNumber: "919944556677",
    from: "Lecture Hall 2",
    to: "Bus Stand",
    date: "2025-05-24",
    time: "1:30 PM",
    seatsAvailable: 1,
    note: "Quick ride, limited luggage please.",
    upvotes: 4,
  },
  {
    id: 9,
    userEmail: "vishal.r@college.edu",
    phoneNumber: "919966778899",
    from: "Block A",
    to: "Railway Station",
    date: "2025-05-25",
    time: "2:15 PM",
    seatsAvailable: 2,
    note: "Looking for quiet co-riders.",
    upvotes: 9,
  },
  {
    id: 10,
    userEmail: "tanvi.m@college.edu",
    phoneNumber: "919900011122",
    from: "Library",
    to: "Airport",
    date: "2025-05-26",
    time: "11:00 AM",
    seatsAvailable: 1,
    note: "No music, early departure.",
    upvotes: 11,
  },
  {
    id: 11,
    userEmail: "deepak.k@college.edu",
    phoneNumber: "919911223344",
    from: "Block B",
    to: "City Mall",
    date: "2025-05-20",
    time: "6:00 PM",
    seatsAvailable: 2,
    note: "Shopping trip, back by evening.",
    upvotes: 5,
  },
  {
    id: 12,
    userEmail: "anita.r@college.edu",
    phoneNumber: "919822334455",
    from: "Cultural Hall",
    to: "Railway Station",
    date: "2025-05-21",
    time: "9:00 AM",
    seatsAvailable: 1,
    note: "No loud music, please.",
    upvotes: 6,
  },
  {
    id: 13,
    userEmail: "yuvraj.g@college.edu",
    phoneNumber: "919933445566",
    from: "Sports Complex",
    to: "ISBT Ranchi",
    date: "2025-05-22",
    time: "8:30 PM",
    seatsAvailable: 3,
    note: "Late night drop after match.",
    upvotes: 7,
  },
  {
    id: 14,
    userEmail: "kanika.m@college.edu",
    phoneNumber: "919844556677",
    from: "Mess Area",
    to: "Bus Stand",
    date: "2025-05-24",
    time: "2:30 PM",
    seatsAvailable: 2,
    note: "Will wait for 10 mins max.",
    upvotes: 8,
  },
  {
    id: 15,
    userEmail: "sahil.v@college.edu",
    phoneNumber: "919955667788",
    from: "Main Gate",
    to: "Airport",
    date: "2025-05-23",
    time: "3:15 PM",
    seatsAvailable: 1,
    note: "Electric car. Smooth ride.",
    upvotes: 10,
  },
  {
    id: 16,
    userEmail: "sanya.t@college.edu",
    phoneNumber: "919900998877",
    from: "Admin Block",
    to: "Railway Station",
    date: "2025-05-25",
    time: "6:45 PM",
    seatsAvailable: 2,
    note: "Can drop at ISBT too if needed.",
    upvotes: 9,
  },
  {
    id: 17,
    userEmail: "manav.k@college.edu",
    phoneNumber: "919988776655",
    from: "Lecture Hall 5",
    to: "City Center",
    date: "2025-05-26",
    time: "5:30 PM",
    seatsAvailable: 3,
    note: "Fun group ride. Snacks included!",
    upvotes: 13,
  }
];

export default carpoolPosts;
